name: Python Autotests

on: [push]

jobs:
  run-tests:
    runs-on: ubunta-latest
    name: Run UI Tests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4
      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install depenndencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest
        
