name: Python Autotests

on:
  workflow_dispatch:
    inputs:
      deplayment_target:
        description: choose tests set
        required: true
        type: choise
        default: smoke
        options:
          - smoke
          - regression
          - all

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run UI Tests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4
      - name: Set up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install depenndencies
        run: pip install -r requirements.txt
      - name: Run All Tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest
      - name: Run Smoke Tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke
      - name: Run Regression Tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression
