name: Python Autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: choose tests set
        required: true
        type: choice
        default: smoke
        options:
          - smoke
          - regression
          - all
          
permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run UI Tests
    steps:
      - name: Checkout autotests
        uses: actions/checkout@v4
      - name: Set up Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install depenndencies
        run: pip install -r requirements.txt
      - name: Run All Tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: pytest --alluredir=allure-results
        continue-on-error: true
      - name: Run Smoke Tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: pytest -m smoke --alluredir=allure-results
        continue-on-error: true
      - name: Run Regression Tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: pytest -m regression --alluredir=allure-results
        continue-on-error: true
      - name: Install java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install allure
        run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz && sudo tar -zxvf allure-2.24.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
      - name: Generate report
        run: allure generate -c allure-results -o _site
      - name: Save allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ github.run_number }}
          path: _site
          retention-days: 30
          
  publish-report:
    runs-on: ubuntu-latest
    name: Report publication
    needs: run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for the pages branch
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report-${{ github.run_number }}
          path: allure-report-${{ github.run_number }}
      - name: Copy reports to gh-pages
        run: |
          mkdir -p public/reports/${{ github.run_number }}
          cp -r allure-report-${{ github.run_number }}/* public/reports/${{ github.run_number }}/
          echo "Report for run ${{ github.run_number }} is available at /reports/${{ github.run_number }}/" >> public/index.html
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4


        
